### ISSUE TITLE
field里输入中文，就不成功啊

### ISSUE THREAD

**Issue by dingyi342** [louietan/anki-editor#49] opened 2019-07-01 09:04 UTC
![deepin-screenshot3770960181](https://user-images.githubusercontent.com/36829022/60423753-70b0ce80-9c21-11e9-9218-5992d2c5a943.png)

**Comment by louietan** [comment] 2019-09-22 12:27
Duplicate of #51. Also the encoding changes for `request.el` has been merged.

**Closed by louietan** 2019-09-22 12:27 UTC
